
# MariaDB or Mysql Server config
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true
#      dialect: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssidev
#    username: root
#    password: root



# Coneccion de sql server
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database: SQL_SERVER
show-sql: true